#!/bin/bash

#PBS -N plsmd_setup
#PBS -P vz35
#PBS -l mem=4GB,ncpus=2,walltime=2:00:00
#PBS -q biodev
#PBS -l storage=gdata/vz35
#PBS -m abe
#PBS -M cameron.jack@anu.edu.au
#PBS -l wd

# You need to qsub this file from wherever the plasmid assembly folder is located. 

### Set these variables and launch with qsub ###

# EMAIL is your email address to get Gadi job messages
EMAIL="cameron.jack@anu.edu.au"

# PROMDATA is the path to the PromethION run containing the plasmids
PROMDATA="ONT_PlasmidSeq_20260218/plasmidpool/20260218_1629_3F_PBE83525_e4822fd3"

# PLASDIR is the name of the directory you want to put the plasmid assemblies in
PLASDIR="plastest1"

# SAMPLESHEET is the path to the sample sheet that describes the plasmid samples, users, plasmid length, and any reference. You make this file!
SAMPLESHEET="ONT_PlasmidSeq_20260218/plasmid_samplesheet_20260218.csv"

### Commands below, add --nodata if you already copied the files, but just want new scripts to be generated

module load python3
python3 plasmid_prep_gadi.py -s "${SAMPLESHEET}" -p "${PLASDIR}" -e "${EMAIL}" "${PROMDATA}"
